services:
  - type: web
    name: hospitalai
    env: python

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
      python -m spacy download en_core_sci_sm

    startCommand: gunicorn main:app
